### ISSUE TITLE
More complicated shaders

### ISSUE THREAD

**Issue by niallrobinson** [met-office-lab/volume-rendering#3]
There are some interesting extensions we can make to the shaders. e.g. we can do internal shadows by passing in the light position. We can also play around with color scales and saturation to make iso-surfaces

**Comment by msaunby** [comment]
As this is 'featured' 'twould be nice if it were spelled proper.

**Comment by niallrobinson** [comment]
go on then

**Comment by niallrobinson** [comment]
Made some progress yesterday on the shadows branch
